name: msfoole
version: 1.0.0
description: 基于swoole4的高性能API服务框架
environments:
  MSFOOLE__HOST: 0.0.0.0
  MSFOOLE__PORT: 9111
  MSFOOLE__SSL: false
  MSFOOLE__MONITOR__SWITCH: true
  MSFOOLE__MONITOR__PATH: app/,config/,vendor/julibo/msfoole-alone/src/
  MSFOOLE__MONITOR__INTERVAL: 3
  MSFOOLE__HEALTH__SWITCH: false
  MSFOOLE__HEALTH__URI: /Index/Index/health
  MSFOOLE__HEALTH__HOST: 127.0.0.1
  MSFOOLE__HEALTH__LIMIT: 3
  MSFOOLE__TABLE__SIZE: 1024
  MSFOOLE__CHANNEL__CAPACITY: 100
  MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
  MSFOOLE__WEBSOCKET__VI: 7AF3C134BEAA99E5
  MSFOOLE__WEBSOCKET__SIGN: null
  MSFOOLE__WEBSOCKET__NAMESPACE: \App\Controller\Robot\
  MSFOOLE__WEBSOCKET__LOGINCLASS: \App\Service\Robot
  MSFOOLE__WEBSOCKET__LOGINACTION: login
  MSFOOLE__OPTION__WORKER_NUM: 1
  MSFOOLE__OPTION__MAX_REQUEST: 10000
  MSFOOLE__OPTION__MAX_CONN: 256
  MSFOOLE__OPTION__DAEMONIZE: false
  MSFOOLE__OPTION__LOG_LEVEL: 0
  MSFOOLE__OPTION__LOG_FILE: msfoole.log
  MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
  MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 120
  MSFOOLE__OPTION__OPEN_HTTP2_PROTOCOL: false
  MSFOOLE__OPTION__RELOAD_ASYNC: true
  MSFOOLE__OPTION__ENABLE_COROUTINE: true
  MSFOOLE__OPTION__MAX_COROUTINE: 3000
  MSFOOLE__OPTION__MAX_WAIT_TIME: 3

  CACHE__DEFAULT__DRIVER: redis
  CACHE__DEFAULT__PREFIX: cache:
  CACHE__DEFAULT__EXPIRE: 3600
  CACHE__DEFAULT__HOST: 127.0.0.1
  CACHE__DEFAULT__PORT: 6379
  CACHE__DEFAULT__PASSWORD:
  CACHE__DEFAULT__DB: 0
  CACHE__DEFAULT__TIMEOUT: 0

  APPLICATION__NAME: msfoole-alone
  APPLICATION__VERSION: 0.0.1
  APPLICATION__DEBUG: true
  APPLICATION__MULTI__MODULE: true
  APPLICATION__DEFAULT__MODULE: Index
  APPLICATION__DEFAULT__CONTROLLER: Index
  APPLICATION__DEFAULT__ACTION: index
  APPLICATION__DEFAULT__KEY: 700040D41F47592C
  APPLICATION__ALLOW__CONTROLLER: App\Controller\Index\Index
  APPLICATION__ACCESS__ORIGIN: http://localhost:8080

  LOG__TYPE: File
  LOG__LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
  LOG__ALLOW_KEY:
  LOG__CLOSE: false
  LOG__PATH: LOG_PATH
  LOG__FILE_SIZE: 2097152
  LOG__APART_LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
  LOG__TIME_FORMAT: c
  LOG__SINGLE: false
  LOG__MAX_FILES: 100
  LOG__SLOW_TIME: 3
  LOG__DEBUG: true
  LOG__RECORD_TRACE: true
  LOG__SORT: false

  COOKIE__PREFIX:
  COOKIE__EXPIRE: 3600
  COOKIE__PATH: /
  COOKIE__DOMAIN:
  COOKIE__SECURE: false
  COOKIE__HTTPONLY:
  COOKIE__TOKEN: TOKEN
  COOKIE__AUTO_SELLING: 600
  COOKIE___CACHE_PREFIX: user: